{
 "nbformat": 4,
 "nbformat_minor": 0,
 "metadata": {
  "colab": {
   "name": "ppo_new.ipynb",
   "provenance": [],
   "collapsed_sections": []
  },
  "kernelspec": {
   "name": "python3",
   "display_name": "Python 3"
  },
  "language_info": {
   "name": "python"
  },
  "accelerator": "GPU"
 },
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {
    "colab": {
     "base_uri": "https://localhost:8080/"
    },
    "cellView": "code",
    "id": "Yhik4sjct8J-",
    "outputId": "9c5fe99e-43d3-4040-97c4-7940594ec353",
    "pycharm": {
     "name": "#%%\n"
    }
   },
   "outputs": [],
   "source": [
    "#@title 默认标题文本\n",
    "\n",
    "import torch\n",
    "import torch.nn as nn\n",
    "import time\n",
    "import retro"
   ]
  },
  {
   "cell_type": "code",
   "source": [
    "env = retro.make(game='Airstriker-Genesis')"
   ],
   "metadata": {
    "id": "5UCpF4F-wI7-",
    "pycharm": {
     "name": "#%%\n"
    }
   },
   "execution_count": 2,
   "outputs": []
  },
  {
   "cell_type": "code",
   "source": [
    "class Actor_NN(nn.Module):\n",
    "    def __init__(self):\n",
    "        super(Actor_NN, self).__init__()\n",
    "        self.cnn = nn.Sequential(\n",
    "            nn.Conv2d(3, 8, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1)),\n",
    "            nn.BatchNorm2d(8, affine=True),\n",
    "            nn.ReLU(),\n",
    "            nn.MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False),\n",
    "            nn.Conv2d(8, 16, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1)),\n",
    "            nn.BatchNorm2d(16, affine=True),\n",
    "            nn.ReLU(),\n",
    "            nn.MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)\n",
    "        )\n",
    "\n",
    "        # self.cnn = models.vgg19(pretrained=True).features.to(DEVICE).eval().requires_grad_(requires_grad=False)\n",
    "        self.pool = nn.Sequential(\n",
    "            nn.AdaptiveAvgPool2d(output_size=(7, 7))\n",
    "        )\n",
    "        self.fc = nn.Sequential(\n",
    "            nn.Linear(784, 128),\n",
    "            nn.BatchNorm1d(128, affine=True),\n",
    "            nn.ReLU(),\n",
    "            nn.Linear(128, 32),\n",
    "            nn.BatchNorm1d(32, affine=True),\n",
    "            nn.ReLU(),\n",
    "            nn.Linear(32, 6),\n",
    "            nn.Softmax(dim=1)\n",
    "        )\n",
    "\n",
    "    def forward(self, x):\n",
    "        x2 = x.permute(0, 3, 2, 1)\n",
    "        y = self.cnn(x2)\n",
    "        y1 = self.pool(y)\n",
    "        y1 = torch.flatten(y1, start_dim=1, end_dim=-1)\n",
    "        z = self.fc(y1)\n",
    "        return z\n",
    "\n",
    "\n",
    "class Critic_NN(nn.Module):\n",
    "    def __init__(self):\n",
    "        super(Critic_NN, self).__init__()\n",
    "        self.cnn = nn.Sequential(\n",
    "            nn.Conv2d(3, 8, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1)),\n",
    "            nn.BatchNorm2d(8, affine=True),\n",
    "            nn.ReLU(),\n",
    "            nn.MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False),\n",
    "            nn.Conv2d(8, 16, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1)),\n",
    "            nn.BatchNorm2d(16, affine=True),\n",
    "            nn.ReLU(),\n",
    "            nn.MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)\n",
    "        )\n",
    "\n",
    "        # self.cnn = models.vgg19(pretrained=True).features.to(DEVICE).eval().requires_grad_(requires_grad=False)\n",
    "        self.pool = nn.Sequential(\n",
    "            nn.AdaptiveAvgPool2d(output_size=(7, 7))\n",
    "        )\n",
    "        self.fc = nn.Sequential(\n",
    "            nn.Linear(784, 64),\n",
    "            nn.BatchNorm1d(64, affine=True),\n",
    "            nn.ReLU(),\n",
    "            nn.Linear(64, 16),\n",
    "            nn.BatchNorm1d(16, affine=True),\n",
    "            nn.ReLU(),\n",
    "            nn.Linear(16, 1),\n",
    "        )\n",
    "\n",
    "    def forward(self, x):\n",
    "        x2 = x.permute(0, 3, 2, 1)\n",
    "        y = self.cnn(x2)\n",
    "        y1 = self.pool(y)\n",
    "        y1 = torch.flatten(y1, start_dim=1, end_dim=-1)\n",
    "        z = self.fc(y1)\n",
    "        return z\n"
   ],
   "metadata": {
    "id": "sloWiVTfwMQ1",
    "pycharm": {
     "name": "#%%\n"
    }
   },
   "execution_count": 3,
   "outputs": []
  },
  {
   "cell_type": "code",
   "source": [
    "class PPO(nn.Module):\n",
    "    def __init__(self, timestep, discount, batch, device, lr, lamb, actor_update, critic_update):\n",
    "        super(PPO, self).__init__()\n",
    "        self.actor_update = actor_update\n",
    "        self.critic_update = critic_update\n",
    "        self.lamb = lamb  \n",
    "        self.lr = lr\n",
    "        self.device = device\n",
    "        self.batch_size = batch\n",
    "        self.timestep = timestep\n",
    "        self.gamma = discount\n",
    "        self.ji = self.lamb * self.gamma\n",
    "        self.coeff = torch.tensor([self.ji**i for i in range(timestep)]).to(self.device)  # 算advantage\n",
    "        self.target_coeff = torch.tensor([self.gamma**i for i in range(timestep)]).to(device) # 算target，折扣因子\n",
    "        self.epsilon = 0.2\n",
    "        self.actor = Actor_NN().to(self.device)\n",
    "        self.old_actor = Actor_NN().to(self.device)\n",
    "        self.critic = Critic_NN().to(self.device)\n",
    "        self.actor_optim = torch.optim.Adam(self.actor.parameters(), lr=self.lr)\n",
    "        self.critic_optim = torch.optim.Adam(self.critic.parameters(), lr=self.lr)\n",
    "        self.discrete_action = []\n",
    "        self.decode_action()\n",
    "\n",
    "    def decode_action(self):\n",
    "        buttons = env.unwrapped.buttons\n",
    "        combos = [[],['B'],['LEFT'],['RIGHT'],['B','LEFT'],['B','RIGHT']]\n",
    "        for combo in combos:\n",
    "            # arr = np.array([0] * env.action_space.n)\n",
    "            arr = [0,0,0,0,0,0,0,0,0,0,0,0]\n",
    "            for button in combo:\n",
    "                arr[buttons.index(button)] = 1\n",
    "            self.discrete_action.append(arr)\n",
    "        # self.discrete_action = np.array(self.discrete_action)\n",
    "\n",
    "    def action_select(self, s):\n",
    "        s = (torch.FloatTensor(s)).to(self.device)\n",
    "        prob = self.actor(s)\n",
    "        dist = torch.distributions.Categorical(prob.squeeze(0))\n",
    "        action = self.discrete_action[dist.sample()]\n",
    "        return action\n",
    "\n",
    "\n",
    "    def actor_learn(self, s, a, advantage):\n",
    "\n",
    "        prob = self.actor(s[:self.batch_size])\n",
    "        pi = torch.distributions.Categorical(prob)\n",
    "\n",
    "        old_prob = self.old_actor(s[:self.batch_size])\n",
    "        old_pi = torch.distributions.Categorical(old_prob)\n",
    "        # print(self.discrete_action)\n",
    "        # print(a)\n",
    "        a = torch.tensor([self.discrete_action.index(list(i.cpu())) for i in a]).to(self.device)\n",
    "        # print(a)\n",
    "        # print(pi.log_prob(a))\n",
    "        # print(old_pi.log_prob(a))\n",
    "        ratio = torch.exp(pi.log_prob(a) - old_pi.log_prob(a))\n",
    "\n",
    "        advantage = torch.tensor(advantage).to(self.device)\n",
    "        surr = (ratio * advantage).reshape(-1,1)  # torch.Size([batch, 1])\n",
    "\n",
    "        # mean取均值，就是期望\n",
    "        # 这个loss就是画面价值，越高越好\n",
    "        loss = -torch.mean(\n",
    "            torch.min(surr, torch.clamp(ratio, 1 - self.epsilon, 1 + self.epsilon) * advantage.reshape(-1, 1)))\n",
    "\n",
    "        self.actor_optim.zero_grad()\n",
    "        loss.backward()\n",
    "        self.actor_optim.step()\n",
    "\n",
    "    def critic_learn(self, targets, s): # 传入s重新计算V而不用self.V一个是因为actor反向传播后会清空梯度，\n",
    "                      # 在这里就无法反向传播了，再一个就是多次反向传播每次都会清空梯度\n",
    "        \n",
    "        self.V = self.critic(s).reshape(self.batch_size+self.timestep)\n",
    "        targets_ = torch.FloatTensor(targets).to(self.device)\n",
    "\n",
    "        loss_func = nn.MSELoss()\n",
    "        # print(targets_.shape)\n",
    "        # print(self.V[:self.batch_size].shape)\n",
    "        loss = loss_func(self.V[:self.batch_size], targets_)\n",
    "\n",
    "        self.critic_optim.zero_grad()\n",
    "        loss.backward()\n",
    "        self.critic_optim.step()\n",
    "\n",
    "    def target_cal(self, r):  # 用于更新critic\n",
    "        targets = []\n",
    "        for i in range(self.batch_size):\n",
    "          # print(r[i].device)\n",
    "          # print(self.V.device)\n",
    "          # print(self.target_coeff.device)\n",
    "          target = r[i] + torch.sum(self.V[i+1:i+self.timestep+1,0]*self.target_coeff)\n",
    "          targets.append(int(target))\n",
    "        \n",
    "        return targets\n",
    "\n",
    "    def delta_cal(self, r, s):  \n",
    "\n",
    "        self.V = self.critic(s)\n",
    "        delta = []\n",
    "        for i in range(len(self.V)-1):\n",
    "            delta0 = r[i] + self.gamma * self.V[i+1,0] - self.V[i,0]\n",
    "            delta.append(int(delta0))\n",
    "\n",
    "        return delta  # 用来计算advantage\n",
    "\n",
    "    def adv_cal(self, delta):\n",
    "\n",
    "        advantage = []\n",
    "        delta_ = torch.tensor(delta).to(self.device)\n",
    "        for i in range(self.batch_size):\n",
    "          adv = torch.sum(self.coeff * delta_[i:i+self.timestep])\n",
    "          advantage.append(int(adv))\n",
    "\n",
    "        return advantage\n",
    "\n",
    "    def update(self, s, a, delta, targets):\n",
    "        self.old_actor.load_state_dict(self.actor.state_dict())\n",
    "        advantage = self.adv_cal(delta)\n",
    "\n",
    "        for i in range(self.actor_update):\n",
    "            self.actor_learn(s, a, advantage)\n",
    "\n",
    "        for i in range(self.critic_update):\n",
    "            self.critic_learn(targets, s)"
   ],
   "metadata": {
    "id": "ZPj5C7l4wPBV",
    "pycharm": {
     "name": "#%%\n"
    }
   },
   "execution_count": 4,
   "outputs": []
  },
  {
   "cell_type": "code",
   "source": [
    "DEVICE = torch.device('cuda')\n",
    "BATCH = 32\n",
    "EPSILON = 0.98\n",
    "DISCOUNT = 0.99\n",
    "TIME_STEP = 256\n",
    "GAE_PARA = 0.95\n",
    "CLIPING = 0.1\n",
    "N_EPISODE = 1201\n",
    "LR = 2.5*1e-4\n",
    "Actor_Update = 3\n",
    "Critic_Update = 3"
   ],
   "metadata": {
    "id": "JmAQT1SwrTlY",
    "pycharm": {
     "name": "#%%\n"
    }
   },
   "execution_count": 5,
   "outputs": []
  },
  {
   "cell_type": "code",
   "source": [
    "env.seed(23)\n",
    "torch.manual_seed(23)\n",
    "\n",
    "agent = PPO(TIME_STEP, DISCOUNT, BATCH, DEVICE, LR, \n",
    "            GAE_PARA, Actor_Update, Critic_Update).to(DEVICE)"
   ],
   "metadata": {
    "id": "20RUNE4xao_U",
    "pycharm": {
     "name": "#%%\n"
    }
   },
   "execution_count": 6,
   "outputs": []
  },
  {
   "cell_type": "code",
   "source": [
    "agent.load_state_dict(torch.load(\"D:\\Python_Projects\\D3QN__Airstriker-Genesis\\models\\ppo_Atari\\ppo_one\\ppo_600.pth\"))"
   ],
   "metadata": {
    "id": "FHP_NT2iatKj",
    "pycharm": {
     "name": "#%%\n"
    }
   },
   "execution_count": 7,
   "outputs": [
    {
     "data": {
      "text/plain": "<All keys matched successfully>"
     },
     "execution_count": 7,
     "metadata": {},
     "output_type": "execute_result"
    }
   ]
  },
  {
   "cell_type": "code",
   "source": [
    "\n",
    "all_ep_r = []\n",
    "s = env.reset()\n",
    "while True:\n",
    "    s = torch.FloatTensor(s[24:,:,:]).unsqueeze(0)\n",
    "    a = agent.eval().action_select(s)\n",
    "    s, r, done, _ = env.step(a)\n",
    "    env.render()\n",
    "    time.sleep(0.012)\n",
    "    if done is True:\n",
    "        s = env.reset()\n"
   ],
   "metadata": {
    "colab": {
     "base_uri": "https://localhost:8080/"
    },
    "id": "ZuKWqhMQwQdh",
    "outputId": "c10b910a-689b-4c55-e9e9-e059c52d7453",
    "pycharm": {
     "name": "#%%\n",
     "is_executing": true
    }
   },
   "execution_count": null,
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "D:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyglet\\image\\codecs\\wic.py:434: UserWarning: [WinError -2147417850] 无法在设置线程模式后对其加以更改。\n",
      "  warnings.warn(str(err))\n",
      "ERROR:root:Internal Python error in the inspect module.\n",
      "Below is the traceback from this internal error.\n",
      "\n",
      "ERROR:root:Internal Python error in the inspect module.\n",
      "Below is the traceback from this internal error.\n",
      "\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Traceback (most recent call last):\n",
      "  File \"D:\\ProgramData\\Anaconda3\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3457, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"C:\\Users\\JACKLE~1\\AppData\\Local\\Temp/ipykernel_43740/4007662215.py\", line 7, in <module>\n",
      "    env.render()\n",
      "  File \"D:\\ProgramData\\Anaconda3\\lib\\site-packages\\retro\\retro_env.py\", line 230, in render\n",
      "    self.viewer.imshow(img)\n",
      "  File \"D:\\ProgramData\\Anaconda3\\lib\\site-packages\\gym\\envs\\classic_control\\rendering.py\", line 449, in imshow\n",
      "    self.window.flip()\n",
      "  File \"D:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyglet\\window\\win32\\__init__.py\", line 388, in flip\n",
      "    self.context.flip()\n",
      "  File \"D:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyglet\\gl\\win32.py\", line 252, in flip\n",
      "    _gdi32.SwapBuffers(self.canvas.hdc)\n",
      "KeyboardInterrupt\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"D:\\ProgramData\\Anaconda3\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2077, in showtraceback\n",
      "    stb = value._render_traceback_()\n",
      "AttributeError: 'KeyboardInterrupt' object has no attribute '_render_traceback_'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"D:\\ProgramData\\Anaconda3\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1101, in get_records\n",
      "    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)\n",
      "  File \"D:\\ProgramData\\Anaconda3\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 248, in wrapped\n",
      "    return f(*args, **kwargs)\n",
      "  File \"D:\\ProgramData\\Anaconda3\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 281, in _fixed_getinnerframes\n",
      "    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))\n",
      "  File \"D:\\ProgramData\\Anaconda3\\lib\\inspect.py\", line 1515, in getinnerframes\n",
      "    frameinfo = (tb.tb_frame,) + getframeinfo(tb, context)\n",
      "  File \"D:\\ProgramData\\Anaconda3\\lib\\inspect.py\", line 1473, in getframeinfo\n",
      "    filename = getsourcefile(frame) or getfile(frame)\n",
      "  File \"D:\\ProgramData\\Anaconda3\\lib\\inspect.py\", line 708, in getsourcefile\n",
      "    if getattr(getmodule(object, filename), '__loader__', None) is not None:\n",
      "  File \"D:\\ProgramData\\Anaconda3\\lib\\inspect.py\", line 751, in getmodule\n",
      "    f = getabsfile(module)\n",
      "  File \"D:\\ProgramData\\Anaconda3\\lib\\inspect.py\", line 720, in getabsfile\n",
      "    _filename = getsourcefile(object) or getfile(object)\n",
      "  File \"D:\\ProgramData\\Anaconda3\\lib\\inspect.py\", line 705, in getsourcefile\n",
      "    if os.path.exists(filename):\n",
      "  File \"D:\\ProgramData\\Anaconda3\\lib\\genericpath.py\", line 19, in exists\n",
      "    os.stat(path)\n",
      "KeyboardInterrupt\n",
      "Traceback (most recent call last):\n",
      "  File \"D:\\ProgramData\\Anaconda3\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3457, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"C:\\Users\\JACKLE~1\\AppData\\Local\\Temp/ipykernel_43740/4007662215.py\", line 7, in <module>\n",
      "    env.render()\n",
      "  File \"D:\\ProgramData\\Anaconda3\\lib\\site-packages\\retro\\retro_env.py\", line 230, in render\n",
      "    self.viewer.imshow(img)\n",
      "  File \"D:\\ProgramData\\Anaconda3\\lib\\site-packages\\gym\\envs\\classic_control\\rendering.py\", line 449, in imshow\n",
      "    self.window.flip()\n",
      "  File \"D:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyglet\\window\\win32\\__init__.py\", line 388, in flip\n",
      "    self.context.flip()\n",
      "  File \"D:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyglet\\gl\\win32.py\", line 252, in flip\n",
      "    _gdi32.SwapBuffers(self.canvas.hdc)\n",
      "KeyboardInterrupt\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"D:\\ProgramData\\Anaconda3\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2077, in showtraceback\n",
      "    stb = value._render_traceback_()\n",
      "AttributeError: 'KeyboardInterrupt' object has no attribute '_render_traceback_'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"D:\\ProgramData\\Anaconda3\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3377, in run_ast_nodes\n",
      "    if (await self.run_code(code, result,  async_=asy)):\n",
      "  File \"D:\\ProgramData\\Anaconda3\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3474, in run_code\n",
      "    self.showtraceback(running_compiled_code=True)\n",
      "  File \"D:\\ProgramData\\Anaconda3\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2079, in showtraceback\n",
      "    stb = self.InteractiveTB.structured_traceback(etype,\n",
      "  File \"D:\\ProgramData\\Anaconda3\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1367, in structured_traceback\n",
      "    return FormattedTB.structured_traceback(\n",
      "  File \"D:\\ProgramData\\Anaconda3\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1267, in structured_traceback\n",
      "    return VerboseTB.structured_traceback(\n",
      "  File \"D:\\ProgramData\\Anaconda3\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1124, in structured_traceback\n",
      "    formatted_exception = self.format_exception_as_a_whole(etype, evalue, etb, number_of_lines_of_context,\n",
      "  File \"D:\\ProgramData\\Anaconda3\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1082, in format_exception_as_a_whole\n",
      "    last_unique, recursion_repeat = find_recursion(orig_etype, evalue, records)\n",
      "  File \"D:\\ProgramData\\Anaconda3\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 382, in find_recursion\n",
      "    return len(records), 0\n",
      "TypeError: object of type 'NoneType' has no len()\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"D:\\ProgramData\\Anaconda3\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2077, in showtraceback\n",
      "    stb = value._render_traceback_()\n",
      "AttributeError: 'TypeError' object has no attribute '_render_traceback_'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"D:\\ProgramData\\Anaconda3\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1101, in get_records\n",
      "    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)\n",
      "  File \"D:\\ProgramData\\Anaconda3\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 248, in wrapped\n",
      "    return f(*args, **kwargs)\n",
      "  File \"D:\\ProgramData\\Anaconda3\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 281, in _fixed_getinnerframes\n",
      "    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))\n",
      "  File \"D:\\ProgramData\\Anaconda3\\lib\\inspect.py\", line 1515, in getinnerframes\n",
      "    frameinfo = (tb.tb_frame,) + getframeinfo(tb, context)\n",
      "  File \"D:\\ProgramData\\Anaconda3\\lib\\inspect.py\", line 1473, in getframeinfo\n",
      "    filename = getsourcefile(frame) or getfile(frame)\n",
      "  File \"D:\\ProgramData\\Anaconda3\\lib\\inspect.py\", line 708, in getsourcefile\n",
      "    if getattr(getmodule(object, filename), '__loader__', None) is not None:\n",
      "  File \"D:\\ProgramData\\Anaconda3\\lib\\inspect.py\", line 754, in getmodule\n",
      "    os.path.realpath(f)] = module.__name__\n",
      "  File \"D:\\ProgramData\\Anaconda3\\lib\\ntpath.py\", line 664, in realpath\n",
      "    if _getfinalpathname(spath) == path:\n",
      "KeyboardInterrupt\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "ERROR:root:Internal Python error in the inspect module.\n",
      "Below is the traceback from this internal error.\n",
      "\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Traceback (most recent call last):\n",
      "  File \"D:\\ProgramData\\Anaconda3\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3457, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"C:\\Users\\JACKLE~1\\AppData\\Local\\Temp/ipykernel_43740/4007662215.py\", line 7, in <module>\n",
      "    env.render()\n",
      "  File \"D:\\ProgramData\\Anaconda3\\lib\\site-packages\\retro\\retro_env.py\", line 230, in render\n",
      "    self.viewer.imshow(img)\n",
      "  File \"D:\\ProgramData\\Anaconda3\\lib\\site-packages\\gym\\envs\\classic_control\\rendering.py\", line 449, in imshow\n",
      "    self.window.flip()\n",
      "  File \"D:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyglet\\window\\win32\\__init__.py\", line 388, in flip\n",
      "    self.context.flip()\n",
      "  File \"D:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyglet\\gl\\win32.py\", line 252, in flip\n",
      "    _gdi32.SwapBuffers(self.canvas.hdc)\n",
      "KeyboardInterrupt\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"D:\\ProgramData\\Anaconda3\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2077, in showtraceback\n",
      "    stb = value._render_traceback_()\n",
      "AttributeError: 'KeyboardInterrupt' object has no attribute '_render_traceback_'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"D:\\ProgramData\\Anaconda3\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3377, in run_ast_nodes\n",
      "    if (await self.run_code(code, result,  async_=asy)):\n",
      "  File \"D:\\ProgramData\\Anaconda3\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3474, in run_code\n",
      "    self.showtraceback(running_compiled_code=True)\n",
      "  File \"D:\\ProgramData\\Anaconda3\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2079, in showtraceback\n",
      "    stb = self.InteractiveTB.structured_traceback(etype,\n",
      "  File \"D:\\ProgramData\\Anaconda3\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1367, in structured_traceback\n",
      "    return FormattedTB.structured_traceback(\n",
      "  File \"D:\\ProgramData\\Anaconda3\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1267, in structured_traceback\n",
      "    return VerboseTB.structured_traceback(\n",
      "  File \"D:\\ProgramData\\Anaconda3\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1124, in structured_traceback\n",
      "    formatted_exception = self.format_exception_as_a_whole(etype, evalue, etb, number_of_lines_of_context,\n",
      "  File \"D:\\ProgramData\\Anaconda3\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1082, in format_exception_as_a_whole\n",
      "    last_unique, recursion_repeat = find_recursion(orig_etype, evalue, records)\n",
      "  File \"D:\\ProgramData\\Anaconda3\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 382, in find_recursion\n",
      "    return len(records), 0\n",
      "TypeError: object of type 'NoneType' has no len()\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"D:\\ProgramData\\Anaconda3\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2077, in showtraceback\n",
      "    stb = value._render_traceback_()\n",
      "AttributeError: 'TypeError' object has no attribute '_render_traceback_'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"D:\\ProgramData\\Anaconda3\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2960, in _run_cell\n",
      "    return runner(coro)\n",
      "  File \"D:\\ProgramData\\Anaconda3\\lib\\site-packages\\IPython\\core\\async_helpers.py\", line 78, in _pseudo_sync_runner\n",
      "    coro.send(None)\n",
      "  File \"D:\\ProgramData\\Anaconda3\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3185, in run_cell_async\n",
      "    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,\n",
      "  File \"D:\\ProgramData\\Anaconda3\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3396, in run_ast_nodes\n",
      "    self.showtraceback()\n",
      "  File \"D:\\ProgramData\\Anaconda3\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2079, in showtraceback\n",
      "    stb = self.InteractiveTB.structured_traceback(etype,\n",
      "  File \"D:\\ProgramData\\Anaconda3\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1367, in structured_traceback\n",
      "    return FormattedTB.structured_traceback(\n",
      "  File \"D:\\ProgramData\\Anaconda3\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1267, in structured_traceback\n",
      "    return VerboseTB.structured_traceback(\n",
      "  File \"D:\\ProgramData\\Anaconda3\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1142, in structured_traceback\n",
      "    formatted_exceptions += self.format_exception_as_a_whole(etype, evalue, etb, lines_of_context,\n",
      "  File \"D:\\ProgramData\\Anaconda3\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1082, in format_exception_as_a_whole\n",
      "    last_unique, recursion_repeat = find_recursion(orig_etype, evalue, records)\n",
      "  File \"D:\\ProgramData\\Anaconda3\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 382, in find_recursion\n",
      "    return len(records), 0\n",
      "TypeError: object of type 'NoneType' has no len()\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"D:\\ProgramData\\Anaconda3\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2077, in showtraceback\n",
      "    stb = value._render_traceback_()\n",
      "AttributeError: 'TypeError' object has no attribute '_render_traceback_'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"D:\\ProgramData\\Anaconda3\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1101, in get_records\n",
      "    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)\n",
      "  File \"D:\\ProgramData\\Anaconda3\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 248, in wrapped\n",
      "    return f(*args, **kwargs)\n",
      "  File \"D:\\ProgramData\\Anaconda3\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 281, in _fixed_getinnerframes\n",
      "    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))\n",
      "  File \"D:\\ProgramData\\Anaconda3\\lib\\inspect.py\", line 1515, in getinnerframes\n",
      "    frameinfo = (tb.tb_frame,) + getframeinfo(tb, context)\n",
      "  File \"D:\\ProgramData\\Anaconda3\\lib\\inspect.py\", line 1473, in getframeinfo\n",
      "    filename = getsourcefile(frame) or getfile(frame)\n",
      "  File \"D:\\ProgramData\\Anaconda3\\lib\\inspect.py\", line 708, in getsourcefile\n",
      "    if getattr(getmodule(object, filename), '__loader__', None) is not None:\n",
      "  File \"D:\\ProgramData\\Anaconda3\\lib\\inspect.py\", line 754, in getmodule\n",
      "    os.path.realpath(f)] = module.__name__\n",
      "  File \"D:\\ProgramData\\Anaconda3\\lib\\ntpath.py\", line 664, in realpath\n",
      "    if _getfinalpathname(spath) == path:\n",
      "KeyboardInterrupt\n"
     ]
    }
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 11,
   "outputs": [
    {
     "data": {
      "text/plain": "tensor([[1., 2., 3.]])"
     },
     "execution_count": 11,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [],
   "metadata": {
    "collapsed": false,
    "pycharm": {
     "name": "#%%\n"
    }
   }
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "outputs": [],
   "source": [],
   "metadata": {
    "collapsed": false,
    "pycharm": {
     "name": "#%%\n"
    }
   }
  }
 ]
}